const components = {
  "Button": "Visual",
  "Card": "Visual",
  "Checkbox": "Visual",
  "CodeVisualizer": "Visual",
  "Details": "Visual",
  "DropDown": "Visual",
  "ElementCarrousel": "Visual",
  "FetchManager": "Service",
  "Grid": "Visual",
  "Icon": "Visual",
  "IndexedDbManager": "Service",
  "Input": "Visual",
  "Layout": "Visual",
  "Link": "Visual",
  "Loading": "Visual",
  "LocalStorageManager": "Service",
  "MultiRoute": "Visual",
  "Navbar": "Visual",
  "NotFound": "Visual",
  "Route": "Visual",
  "Select": "Visual",
  "Switch": "Visual",
  "Table": "Visual",
  "Tabs": "Visual",
  "ThemeSelector": "Visual",
  "TreeItem": "Visual",
  "TreeView": "Visual",

  // FitSlice Services
  "AuthService": "Service",
  "ProfileService": "Service",
  "PlanService": "Service",
  "ChatService": "Service",
  "ExerciseService": "Service",

  // FitSlice Pages
  "LoginPage": "Visual",
  "RegisterPage": "Visual",
  "OnboardingPage": "Visual",
  "DashboardPage": "Visual",
  "ChatPage": "Visual",
  "ExercisePage": "Visual",
};

export default components;